import os, json, re, shutil
root='/mnt/data/v17'
# Build a 220-track catalog (metadata/search links only; no copyrighted audio is redistributed).
arabic = [
('Amr Diab','Tamally Maak'),('Amr Diab','Nour El Ein'),('Amr Diab','Leily Nahary'),('Amr Diab','Wala Ala Balo'),('Amr Diab','Amaken El Sahar'),('Amr Diab','Bahebak Ana'),('Amr Diab','Ya Ana Ya La'),('Amr Diab','Kammel Kalamak'),('Amr Diab','El Leila'),('Amr Diab','Ayesh'),
('Tamer Hosny','Bahebbak Enta'),('Tamer Hosny','180 Daraga'),('Tamer Hosny','Naseny Leh'),('Tamer Hosny','Ya Ana Ya Mafesh'),('Tamer Hosny','Hob'),('Tamer Hosny','Kol Elly Leik'),('Tamer Hosny','Eish Beshoak'),('Tamer Hosny','Oudi'),('Tamer Hosny','Law Hata'),('Tamer Hosny','Ergaaly'),
('Tamer Ashour','Thawani'),('Tamer Ashour','Haygely Mawgou'),('Tamer Ashour','Khalleeny Fi Hodnak'),('Tamer Ashour','Khally Shoaya'),('Tamer Ashour','Mabaarafsh'),('Tamer Ashour','Tagen'),('Tamer Ashour','Awel Mara'),('Tamer Ashour','Hekayat El Hob'),('Tamer Ashour','Mashy'),('Tamer Ashour','Thawany'),
('Ramy Sabry','Kelmni Shwaya'),('Ramy Sabry','Alamany'),('Ramy Sabry','Hob El Omr'),('Ramy Sabry','Mosh Betghib'),('Ramy Sabry','Ahd El Hob'),('Ramy Sabry','Khod Balak'),('Ramy Sabry','Banafs'),('Ramy Sabry','Forsa Tania'),('Ramy Sabry','Mabrouk Alina'),('Ramy Sabry','Law Kont'),
('Sherine','Kollaha Gherana'),('Sherine','Keda Ya Alby'),('Sherine','Mashaer'),('Sherine','Asef'),('Sherine','Sabry Aleel'),('Sherine','El Watar El Hassas'),('Sherine','Hobbo Ganna'),('Sherine','Qalbi Leek'),('Sherine','Kolly Melkak'),('Sherine','Ana Keteer'),
('Nancy Ajram','Ah W Noss'),('Nancy Ajram','Ya Tabtab Wa Dallaa'),('Nancy Ajram','Badna Nwalee El Jaw'),('Nancy Ajram','Inta Eyh'),('Nancy Ajram','Fi Hagat'),('Nancy Ajram','Lawn Ouyounak'),('Nancy Ajram','Ma Tegi Hena'),('Nancy Ajram','Lamset Eed'),('Nancy Ajram','Ehsas Jdeed'),('Nancy Ajram','Albi Ya Albi'),
('Mohamed Hamaki','Bahebak Kol Youm Aktar'),('Mohamed Hamaki','Nefsi Aboulo'),('Mohamed Hamaki','La Malama'),('Mohamed Hamaki','Ahla Haga Feki'),('Mohamed Hamaki','Akhteer'),('Mohamed Hamaki','Min Alby Ba2olak'),('Mohamed Hamaki','Baed El Layaly'),('Mohamed Hamaki','Haga Mestakhabeya'),('Mohamed Hamaki','Kalamak Habibi'),('Mohamed Hamaki','Daa Albi'),
('Elissa','Aayshalak'),('Elissa','Hob Kol Hayaty'),('Elissa','Aa Bali Habibi'),('Elissa','Krahni'),('Elissa','Betmoun'),('Elissa','Maktooba Leek'),('Elissa','Law'),('Elissa','Sahbit Raey'),('Elissa','Ana W Bass'),('Elissa','Waja El Hawa'),
('Wael Kfoury','Law Hobna Ghalta'),('Wael Kfoury','Omri Kello'),('Wael Kfoury','Ya Dalia'),('Wael Kfoury','El Bint El Awiye'),('Wael Kfoury','Hobak Azab'),('Wael Kfoury','Qalbi Meshta2'),('Wael Kfoury','Ma Fi Shi'),('Wael Kfoury','Hokm El Alb'),('Wael Kfoury','Sarne El Leil'),('Wael Kfoury','Baddi Yaak'),
('Angham','Sidi Wesalak'),('Angham','Omry Maak'),('Angham','Lama Baak'),('Angham','Aolak Eh'),('Angham','Atmana'),('Angham','Hala Khassa Gedan'),('Angham','Le Farah'),('Angham','El Hob',),('Angham','Hallem'),('Angham','Btewseeni'),
('Hussain Al Jassmi','Boshret Kheir'),('Hussain Al Jassmi','Bel Bont El3areed'),('Hussain Al Jassmi','Ahebek'),('Hussain Al Jassmi','Set El Kol'),('Hussain Al Jassmi','Feeky Ya Helwa'),('Hussain Al Jassmi','Roh El Salam'),('Hussain Al Jassmi','Ya Shams'),('Hussain Al Jassmi','Allah Ya Allah'),('Hussain Al Jassmi','Mahabesh Ghery'),('Hussain Al Jassmi','El Ghali'),
('Assala','Shokran'),('Assala','Bent Akaber'),('Assala','Foq'),('Assala','60 Daqeeqa Hayat'),('Assala','Khod El Gharam'),('Assala','Ya Magnoun'),('Assala','Aadi'),('Assala','Maafish Menak'),('Assala','Shayfa Feek'),('Assala','Ghalban'),
]
foreign = [
('The Weeknd','Blinding Lights'),('The Weeknd','Starboy'),('The Weeknd','Save Your Tears'),('The Weeknd','The Hills'),('The Weeknd','Die For You'),('The Weeknd','Call Out My Name'),('The Weeknd','After Hours'),('The Weeknd','I Feel It Coming'),('The Weeknd','Earned It'),('The Weeknd','Out of Time'),
('Ed Sheeran','Shape of You'),('Ed Sheeran','Perfect'),('Ed Sheeran','Photograph'),('Ed Sheeran','Thinking Out Loud'),('Ed Sheeran','Bad Habits'),('Ed Sheeran','Shivers'),('Ed Sheeran','Castle on the Hill'),('Ed Sheeran','Galway Girl'),('Ed Sheeran','Happier'),('Ed Sheeran','Eyes Closed'),
('Taylor Swift','Anti-Hero'),('Taylor Swift','Blank Space'),('Taylor Swift','Cruel Summer'),('Taylor Swift','Style'),('Taylor Swift','Love Story'),('Taylor Swift','Cardigan'),('Taylor Swift','Delicate'),('Taylor Swift','Lover'),('Taylor Swift','Wildest Dreams'),('Taylor Swift','Shake It Off'),
('Adele','Hello'),('Adele','Easy On Me'),('Adele','Someone Like You'),('Adele','Rolling in the Deep'),('Adele','Set Fire to the Rain'),('Adele','When We Were Young'),('Adele','Send My Love'),('Adele','Skyfall'),('Adele','Water Under the Bridge'),('Adele','Hometown Glory'),
('Bruno Mars','Just the Way You Are'),('Bruno Mars','Locked Out of Heaven'),('Bruno Mars','Uptown Funk'),('Bruno Mars','Grenade'),('Bruno Mars','When I Was Your Man'),('Bruno Mars','That’s What I Like'),('Bruno Mars','24K Magic'),('Bruno Mars','Talking to the Moon'),('Bruno Mars','Treasure'),('Bruno Mars','Versace on the Floor'),
('Billie Eilish','bad guy'),('Billie Eilish','lovely'),('Billie Eilish','Happier Than Ever'),('Billie Eilish','ocean eyes'),('Billie Eilish','everything i wanted'),('Billie Eilish','when the party is over'),('Billie Eilish','What Was I Made For?'),('Billie Eilish','BIRDS OF A FEATHER'),('Billie Eilish','Therefore I Am'),('Billie Eilish','Lunch'),
('Dua Lipa','Levitating'),('Dua Lipa','New Rules'),('Dua Lipa','Don’t Start Now'),('Dua Lipa','Houdini'),('Dua Lipa','Physical'),('Dua Lipa','Love Again'),('Dua Lipa','Break My Heart'),('Dua Lipa','One Kiss'),('Dua Lipa','Training Season'),('Dua Lipa','Dance the Night'),
('Harry Styles','As It Was'),('Harry Styles','Watermelon Sugar'),('Harry Styles','Adore You'),('Harry Styles','Sign of the Times'),('Harry Styles','Late Night Talking'),('Harry Styles','Falling'),('Harry Styles','Golden'),('Harry Styles','Music for a Sushi Restaurant'),('Harry Styles','Satellite'),('Harry Styles','Lights Up'),
('Justin Bieber','Sorry'),('Justin Bieber','Love Yourself'),('Justin Bieber','Peaches'),('Justin Bieber','Stay'),('Justin Bieber','What Do You Mean?'),('Justin Bieber','Ghost'),('Justin Bieber','Company'),('Justin Bieber','Yummy'),('Justin Bieber','Anyone'),('Justin Bieber','Intentions'),
('Rihanna','Diamonds'),('Rihanna','Umbrella'),('Rihanna','Stay'),('Rihanna','We Found Love'),('Rihanna','Only Girl'),('Rihanna','Love on the Brain'),('Rihanna','Work'),('Rihanna','Needed Me'),('Rihanna','Disturbia'),('Rihanna','Where Have You Been'),
('Coldplay','Yellow'),('Coldplay','Fix You'),('Coldplay','Viva La Vida'),('Coldplay','The Scientist'),('Coldplay','A Sky Full of Stars'),('Coldplay','Paradise'),('Coldplay','Clocks'),('Coldplay','Adventure of a Lifetime'),('Coldplay','Hymn for the Weekend'),('Coldplay','Something Just Like This'),
('Maroon 5','Sugar'),('Maroon 5','Memories'),('Maroon 5','Girls Like You'),('Maroon 5','Maps'),('Maroon 5','Payphone'),('Maroon 5','Animals'),('Maroon 5','This Love'),('Maroon 5','She Will Be Loved'),('Maroon 5','Moves Like Jagger'),('Maroon 5','Beautiful Mistakes'),
('OneRepublic','Counting Stars'),('OneRepublic','Apologize'),('OneRepublic','I Lived'),('OneRepublic','Secrets'),('OneRepublic','Run'),('OneRepublic','Good Life'),('OneRepublic','If I Lose Myself'),('OneRepublic','Love Runs Out'),('OneRepublic','Rescue Me'),('OneRepublic','Sunshine'),
]
# Ensure >200 unique records
tracks=[]
seen=set()
for lang, rows in [('ar',arabic),('en',foreign)]:
    for artist,title in rows:
        key=(artist.lower(),title.lower())
        if key not in seen:
            seen.add(key); tracks.append({'id':f'catalog-{len(tracks)+1:03d}','language':lang,'artist':artist,'title':title,'type':'external','search':f'https://www.youtube.com/results?search_query={artist} {title}'.replace(' ','+')})
assert len(tracks)>=200, len(tracks)
with open(os.path.join(root,'music_catalog.json'),'w',encoding='utf-8') as f: json.dump(tracks,f,ensure_ascii=False,indent=2)
# Add production deployment assets
os.makedirs(os.path.join(root,'deploy'),exist_ok=True)
open(os.path.join(root,'deploy','nginx.conf'),'w').write('''server {\n  listen 443 ssl http2;\n  server_name your-domain.example;\n  ssl_certificate /etc/letsencrypt/live/your-domain.example/fullchain.pem;\n  ssl_certificate_key /etc/letsencrypt/live/your-domain.example/privkey.pem;\n  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;\n  location / { proxy_pass http://127.0.0.1:3000; proxy_http_version 1.1; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto https; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; }\n}\nserver { listen 80; server_name your-domain.example; return 301 https://$host$request_uri; }\n''')
open(os.path.join(root,'deploy','docker-compose.turn.yml'),'w').write('''services:\n  coturn:\n    image: coturn/coturn:latest\n    restart: unless-stopped\n    command: >-\n      -n --log-file=stdout --fingerprint --lt-cred-mech\n      --realm=your-domain.example --user=turnuser:CHANGE_THIS_LONG_PASSWORD\n      --min-port=49160 --max-port=49200 --no-cli\n    ports:\n      - "3478:3478/udp"\n      - "3478:3478/tcp"\n      - "49160-49200:49160-49200/udp"\n''')
# Improve env example
p=os.path.join(root,'.env.example'); s=open(p).read();
s=s.replace('TURN_URLS=\nTURN_USERNAME=\nTURN_CREDENTIAL=','TURN_URLS=turn:your-domain.example:3478,turns:your-domain.example:5349\nTURN_USERNAME=turnuser\nTURN_CREDENTIAL=CHANGE_THIS_LONG_RANDOM_PASSWORD\n')
open(p,'w').write(s)
# Replace local music script with catalog-aware UI while preserving local tracks.
js=r'''(function(){
"use strict";
function initLocalMusic(){
 if(document.getElementById("ze-local-music"))return;
 const s=document.createElement("style");s.textContent=`#ze-local-music{position:fixed;right:18px;bottom:86px;z-index:100004;width:min(390px,calc(100vw - 30px));max-height:70vh;overflow:auto;padding:14px;border-radius:18px;background:rgba(10,15,35,.97);color:#fff;box-shadow:0 15px 45px rgba(0,0,0,.35);font:700 13px system-ui;display:none;backdrop-filter:blur(12px)}#ze-local-music.open{display:block}#ze-local-music select,#ze-local-music input{width:100%;margin:7px 0}#ze-local-music button{border:0;border-radius:10px;padding:8px 11px;margin:3px;background:#24304d;color:#fff;font-weight:800;cursor:pointer}#ze-local-music .primary{background:linear-gradient(135deg,#00c6ff,#7c3aed)}#ze-music-fab-v18{position:fixed;right:18px;bottom:18px;z-index:100005;width:58px;height:58px;border:0;border-radius:50%;background:linear-gradient(135deg,#00e5ff,#7c3aed);color:#fff;font-size:24px;box-shadow:0 10px 35px rgba(0,0,0,.35);touch-action:none}.ze-cat{display:flex;gap:5px;flex-wrap:wrap}.ze-cat button.active{outline:2px solid #fff}.ze-track{padding:8px;border-radius:10px;background:rgba(255,255,255,.07);margin:5px 0}.ze-track small{opacity:.7}.ze-track a{color:#9ee7ff;text-decoration:none;float:right}`;document.head.appendChild(s);
 const p=document.createElement("div");p.id="ze-local-music";p.innerHTML=`<div style="font-size:16px">🎵 Zeyad Music V18</div><div style="opacity:.7;margin:3px 0 8px">11 مسارات محلية + 220 أغنية عربية وأجنبية (روابط بحث قانونية؛ لا يتم توزيع ملفات صوتية محمية).</div><select id="ze-track-v18"><option value="music/neon_penguin_rush.wav">🐧 Neon Penguin Rush</option><option value="music/ai_arcade_chill.wav">🤖 AI Arcade Chill</option><option value="music/victory_party.wav">🏆 Victory Party</option><option value="music/neon_night.wav">🌃 Neon Night</option><option value="music/pixel_dreams.wav">🕹️ Pixel Dreams</option><option value="music/cyber_sunset.wav">🌅 Cyber Sunset</option><option value="music/arcade_breeze.wav">🎮 Arcade Breeze</option><option value="music/penguin_parade.wav">🐧 Penguin Parade</option><option value="music/galaxy_drive.wav">🌌 Galaxy Drive</option><option value="music/victory_lights.wav">🏆 Victory Lights</option><option value="music/chill_ai.wav">🧠 Chill AI</option></select><audio id="ze-audio-v18" preload="auto"></audio><button class="primary" id="ze-play-v18">▶ تشغيل</button><button id="ze-prev-v18">⏮</button><button id="ze-next-v18">⏭</button><button id="ze-shuffle-v18">🔀 عشوائي</button><button id="ze-repeat-v18">🔁 تكرار</button><label style="display:block;margin-top:5px">🔊 <input id="ze-vol-v18" type="range" min="0" max="1" step=".01" value=".65"></label><hr><input id="ze-search-v18" placeholder="🔎 ابحث عن أغنية أو فنان"><div class="ze-cat"><button id="ze-ar-v18">🇪🇬 عربي</button><button id="ze-en-v18">🌍 أجنبي</button><button id="ze-all-v18" class="active">✨ الكل</button></div><div id="ze-catalog-v18"></div>`;document.body.appendChild(p);
 const fab=document.createElement("button");fab.id="ze-music-fab-v18";fab.textContent="🎵";fab.title="الموسيقى";document.body.appendChild(fab);
 const audio=p.querySelector("#ze-audio-v18"),sel=p.querySelector("#ze-track-v18");let idx=0,shuffle=false,repeat=false, catalog=[],filter='all';
 function load(){audio.src=sel.value;audio.load();sel.selectedIndex=idx}
 function next(){idx=shuffle?Math.floor(Math.random()*sel.options.length):(idx+1)%sel.options.length;load();audio.play().catch(()=>{});p.querySelector('#ze-play-v18').textContent='⏸ إيقاف'}
 sel.onchange=()=>{idx=sel.selectedIndex;load();audio.play().catch(()=>{})};p.querySelector('#ze-play-v18').onclick=()=>{if(audio.paused){audio.play().catch(()=>{});p.querySelector('#ze-play-v18').textContent='⏸ إيقاف'}else{audio.pause();p.querySelector('#ze-play-v18').textContent='▶ تشغيل'}};p.querySelector('#ze-prev-v18').onclick=()=>{idx=(idx-1+sel.options.length)%sel.options.length;load();audio.play().catch(()=>{})};p.querySelector('#ze-next-v18').onclick=next;p.querySelector('#ze-shuffle-v18').onclick=()=>{shuffle=!shuffle;p.querySelector('#ze-shuffle-v18').textContent=shuffle?'🔀 عشوائي ✓':'🔀 عشوائي'};p.querySelector('#ze-repeat-v18').onclick=()=>{repeat=!repeat;p.querySelector('#ze-repeat-v18').textContent=repeat?'🔁 تكرار ✓':'🔁 تكرار'};p.querySelector('#ze-vol-v18').oninput=e=>audio.volume=e.target.value;audio.onended=()=>repeat?audio.play():next();load();audio.volume=.65;
 async function loadCatalog(){try{catalog=await fetch('music_catalog.json',{cache:'no-store'}).then(r=>r.ok?r.json():[]);render()}catch(e){catalog=[]}}
 function render(){const q=(p.querySelector('#ze-search-v18').value||'').toLowerCase();const rows=catalog.filter(t=>(filter==='all'||t.language===filter)&&((t.artist+' '+t.title).toLowerCase().includes(q))).slice(0,80);p.querySelector('#ze-catalog-v18').innerHTML=rows.map(t=>`<div class="ze-track"><div>🎵 ${escapeHtml(t.title)}</div><small>${escapeHtml(t.artist)} · ${t.language==='ar'?'عربي':'English'}</small><a target="_blank" rel="noopener noreferrer" href="${t.search}">استماع ↗</a></div>`).join('')||'<div style="opacity:.7;padding:10px">لا توجد نتائج.</div>'}
 function escapeHtml(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 p.querySelector('#ze-search-v18').oninput=render;p.querySelector('#ze-ar-v18').onclick=()=>{filter='ar';document.querySelectorAll('.ze-cat button').forEach(b=>b.classList.remove('active'));p.querySelector('#ze-ar-v18').classList.add('active');render()};p.querySelector('#ze-en-v18').onclick=()=>{filter='en';document.querySelectorAll('.ze-cat button').forEach(b=>b.classList.remove('active'));p.querySelector('#ze-en-v18').classList.add('active');render()};p.querySelector('#ze-all-v18').onclick=()=>{filter='all';document.querySelectorAll('.ze-cat button').forEach(b=>b.classList.remove('active'));p.querySelector('#ze-all-v18').classList.add('active');render()};
 loadCatalog();let open=false;fab.onclick=()=>{open=!open;p.classList.toggle('open',open)};
 let drag=false,sx=0,sy=0,ox=0,oy=0;fab.onpointerdown=e=>{drag=true;sx=e.clientX;sy=e.clientY;let r=fab.getBoundingClientRect();ox=r.left;oy=r.top;fab.setPointerCapture(e.pointerId)};fab.onpointermove=e=>{if(!drag)return;let dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)+Math.abs(dy)>7)fab.dataset.dragged='1';fab.style.left=Math.max(4,Math.min(innerWidth-66,ox+dx))+'px';fab.style.top=Math.max(4,Math.min(innerHeight-66,oy+dy))+'px';fab.style.right='auto';fab.style.bottom='auto'};fab.onpointerup=()=>{drag=false};window.ZeyadLocalMusic={audio,play:()=>audio.play(),pause:()=>audio.pause()};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initLocalMusic);else initLocalMusic();})();
'''
open(os.path.join(root,'zeyad_local_music_v18.js'),'w').write(js)
# Point index to V18
idxp=os.path.join(root,'public','index.html'); html=open(idxp,encoding='utf-8').read().replace('zeyad_local_music_v14.js','../zeyad_local_music_v18.js'); open(idxp,'w',encoding='utf-8').write(html)
# Production docs
open(os.path.join(root,'SECURITY_PRODUCTION_V18.md'),'w').write('''# V18 Production Security\n\n- HTTPS: terminate TLS at Nginx using `deploy/nginx.conf`, then set `TRUST_PROXY=1` and `FORCE_HSTS=1`.\n- TURN: run Coturn using `deploy/docker-compose.turn.yml`, replace the placeholder password, expose UDP 3478 and a restricted relay range, then set TURN_URLS/TURN_USERNAME/TURN_CREDENTIAL in `.env`.\n- Never commit `.env`, TURN credentials, or TLS private keys.\n- Use a firewall so Node port 3000 is private/localhost only.\n- Rotate TURN credentials periodically; for stronger deployments use time-limited TURN credentials generated by your TURN provider.\n- Keep the 220-track catalog as links/metadata unless you have distribution rights for audio files.\n''')
