(function(){
"use strict";
function initLocalMusic(){
 if(document.getElementById("ze-local-music"))return;
 const s=document.createElement("style");s.textContent=`#ze-local-music{position:fixed;right:18px;bottom:86px;z-index:100004;width:min(390px,calc(100vw - 30px));max-height:70vh;overflow:auto;padding:14px;border-radius:18px;background:rgba(10,15,35,.97);color:#fff;box-shadow:0 15px 45px rgba(0,0,0,.35);font:700 13px system-ui;display:none;backdrop-filter:blur(12px)}#ze-local-music.open{display:block}#ze-local-music select,#ze-local-music input{width:100%;margin:7px 0}#ze-local-music button{border:0;border-radius:10px;padding:8px 11px;margin:3px;background:#24304d;color:#fff;font-weight:800;cursor:pointer}#ze-local-music .primary{background:linear-gradient(135deg,#00c6ff,#7c3aed)}#ze-music-fab-v18{position:fixed;right:18px;bottom:18px;z-index:100005;width:58px;height:58px;border:0;border-radius:50%;background:linear-gradient(135deg,#00e5ff,#7c3aed);color:#fff;font-size:24px;box-shadow:0 10px 35px rgba(0,0,0,.35);touch-action:none}.ze-cat{display:flex;gap:5px;flex-wrap:wrap}.ze-cat button.active{outline:2px solid #fff}.ze-track{padding:8px;border-radius:10px;background:rgba(255,255,255,.07);margin:5px 0}.ze-track small{opacity:.7}.ze-track a{color:#9ee7ff;text-decoration:none;float:right}`;document.head.appendChild(s);
 const p=document.createElement("div");p.id="ze-local-music";p.innerHTML=`<div style="font-size:16px">🎵 Zeyad Music V18</div><div style="opacity:.7;margin:3px 0 8px">11 مسارات محلية + 220 أغنية عربية وأجنبية (روابط بحث قانونية؛ لا يتم توزيع ملفات صوتية محمية).</div><select id="ze-track-v18"><option value="music/neon_penguin_rush.wav">🐧 Neon Penguin Rush</option><option value="music/ai_arcade_chill.wav">🤖 AI Arcade Chill</option><option value="music/victory_party.wav">🏆 Victory Party</option><option value="music/neon_night.wav">🌃 Neon Night</option><option value="music/pixel_dreams.wav">🕹️ Pixel Dreams</option><option value="music/cyber_sunset.wav">🌅 Cyber Sunset</option><option value="music/arcade_breeze.wav">🎮 Arcade Breeze</option><option value="music/penguin_parade.wav">🐧 Penguin Parade</option><option value="music/galaxy_drive.wav">🌌 Galaxy Drive</option><option value="music/victory_lights.wav">🏆 Victory Lights</option><option value="music/chill_ai.wav">🧠 Chill AI</option></select><audio id="ze-audio-v18" preload="auto"></audio><button class="primary" id="ze-play-v18">▶ تشغيل</button><button id="ze-prev-v18">⏮</button><button id="ze-next-v18">⏭</button><button id="ze-shuffle-v18">🔀 عشوائي</button><button id="ze-repeat-v18">🔁 تكرار</button><label style="display:block;margin-top:5px">🔊 <input id="ze-vol-v18" type="range" min="0" max="1" step=".01" value=".65"></label><hr><input id="ze-search-v18" placeholder="🔎 ابحث عن أغنية أو فنان"><div class="ze-cat"><button id="ze-ar-v18">🇪🇬 عربي</button><button id="ze-en-v18">🌍 أجنبي</button><button id="ze-all-v18" class="active">✨ الكل</button></div><div id="ze-catalog-v18"></div>`;document.body.appendChild(p);
 const fab=document.createElement("button");fab.id="ze-music-fab-v18";fab.textContent="🎵";fab.title="الموسيقى";document.body.appendChild(fab);
 const audio=p.querySelector("#ze-audio-v18"),sel=p.querySelector("#ze-track-v18");let idx=0,shuffle=false,repeat=false, catalog=[],filter='all';
 function load(){audio.src=sel.value;audio.load();sel.selectedIndex=idx}
 function next(){idx=shuffle?Math.floor(Math.random()*sel.options.length):(idx+1)%sel.options.length;load();audio.play().catch(()=>{});p.querySelector('#ze-play-v18').textContent='⏸ إيقاف'}
 sel.onchange=()=>{idx=sel.selectedIndex;load();audio.play().catch(()=>{})};p.querySelector('#ze-play-v18').onclick=()=>{if(audio.paused){audio.play().catch(()=>{});p.querySelector('#ze-play-v18').textContent='⏸ إيقاف'}else{audio.pause();p.querySelector('#ze-play-v18').textContent='▶ تشغيل'}};p.querySelector('#ze-prev-v18').onclick=()=>{idx=(idx-1+sel.options.length)%sel.options.length;load();audio.play().catch(()=>{})};p.querySelector('#ze-next-v18').onclick=next;p.querySelector('#ze-shuffle-v18').onclick=()=>{shuffle=!shuffle;p.querySelector('#ze-shuffle-v18').textContent=shuffle?'🔀 عشوائي ✓':'🔀 عشوائي'};p.querySelector('#ze-repeat-v18').onclick=()=>{repeat=!repeat;p.querySelector('#ze-repeat-v18').textContent=repeat?'🔁 تكرار ✓':'🔁 تكرار'};p.querySelector('#ze-vol-v18').oninput=e=>audio.volume=e.target.value;audio.onended=()=>repeat?audio.play():next();load();audio.volume=.65;
 async function loadCatalog(){try{catalog=await fetch('music_catalog.json',{cache:'no-store'}).then(r=>r.ok?r.json():[]);render()}catch(e){catalog=[]}}
 function render(){const q=(p.querySelector('#ze-search-v18').value||'').toLowerCase();const rows=catalog.filter(t=>(filter==='all'||t.language===filter)&&((t.artist+' '+t.title).toLowerCase().includes(q))).slice(0,80);p.querySelector('#ze-catalog-v18').innerHTML=rows.map(t=>`<div class="ze-track"><div>🎵 ${escapeHtml(t.title)}</div><small>${escapeHtml(t.artist)} · ${t.language==='ar'?'عربي':'English'}</small><a target="_blank" rel="noopener noreferrer" href="${t.search}">استماع ↗</a></div>`).join('')||'<div style="opacity:.7;padding:10px">لا توجد نتائج.</div>'}
 function escapeHtml(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 p.querySelector('#ze-search-v18').oninput=render;p.querySelector('#ze-ar-v18').onclick=()=>{filter='ar';document.querySelectorAll('.ze-cat button').forEach(b=>b.classList.remove('active'));p.querySelector('#ze-ar-v18').classList.add('active');render()};p.querySelector('#ze-en-v18').onclick=()=>{filter='en';document.querySelectorAll('.ze-cat button').forEach(b=>b.classList.remove('active'));p.querySelector('#ze-en-v18').classList.add('active');render()};p.querySelector('#ze-all-v18').onclick=()=>{filter='all';document.querySelectorAll('.ze-cat button').forEach(b=>b.classList.remove('active'));p.querySelector('#ze-all-v18').classList.add('active');render()};
 loadCatalog();let open=false;fab.onclick=()=>{open=!open;p.classList.toggle('open',open)};
 let drag=false,sx=0,sy=0,ox=0,oy=0;fab.onpointerdown=e=>{drag=true;sx=e.clientX;sy=e.clientY;let r=fab.getBoundingClientRect();ox=r.left;oy=r.top;fab.setPointerCapture(e.pointerId)};fab.onpointermove=e=>{if(!drag)return;let dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)+Math.abs(dy)>7)fab.dataset.dragged='1';fab.style.left=Math.max(4,Math.min(innerWidth-66,ox+dx))+'px';fab.style.top=Math.max(4,Math.min(innerHeight-66,oy+dy))+'px';fab.style.right='auto';fab.style.bottom='auto'};fab.onpointerup=()=>{drag=false};window.ZeyadLocalMusic={audio,play:()=>audio.play(),pause:()=>audio.pause()};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initLocalMusic);else initLocalMusic();})();
