(function(){
'use strict';
function initSocial(){
 if(document.getElementById('ze-social'))return;
 const s=document.createElement('style');s.textContent=`
#ze-social{position:fixed;inset:0;z-index:100006;background:rgba(3,7,18,.76);backdrop-filter:blur(10px);display:none;align-items:center;justify-content:center;font-family:system-ui,sans-serif}
#ze-social.open{display:flex}#ze-chat-app{width:min(98vw,1100px);height:min(92vh,720px);display:grid;grid-template-columns:285px 1fr;background:#f5f7fb;border-radius:24px;overflow:hidden;box-shadow:0 25px 90px #0008}
#ze-chat-side{background:#0d1728;color:#fff;display:flex;flex-direction:column}#ze-chat-brand{padding:18px;font-size:20px;font-weight:950;border-bottom:1px solid #ffffff18}#ze-chat-search{margin:12px;padding:11px 13px;border-radius:13px;border:1px solid #ffffff12;background:#18243a;color:#fff;outline:0}
#ze-social-tools{display:flex;gap:6px;padding:0 12px 10px;flex-wrap:wrap}#ze-social-tools button{flex:1;border:1px solid #ffffff12;background:#18243a;color:#fff;border-radius:11px;padding:9px 7px;font-weight:900;cursor:pointer;font-size:11px}#ze-social-tools button.active{background:#2563eb}
#ze-status-panel,#ze-mod-panel{display:none;overflow:auto;flex:1;padding:12px}.ze-status-card{background:#fff;color:#111827;border-radius:17px;padding:13px;margin:8px 0;box-shadow:0 3px 12px #0001}.ze-status-top{display:flex;gap:9px;align-items:center;font-weight:900}.ze-status-text{margin-top:9px;line-height:1.6}.ze-sticker-big{font-size:62px;text-align:center;padding:8px}.ze-mod-msg{background:#fff;color:#111827;border-radius:15px;padding:10px 12px;margin:7px 0}.ze-mod-msg.me{background:#dbeafe}.ze-role{font-size:9px;color:#64748b;margin-right:5px}.ze-sticker-panel{display:none;gap:5px;flex-wrap:wrap;padding:8px;background:#f8fafc;border-top:1px solid #e5e7eb}.ze-sticker-panel.open{display:flex}.ze-sticker{border:0;background:#eef2ff;border-radius:12px;padding:7px;font-size:25px;cursor:pointer}
#ze-contacts{overflow:auto;flex:1}.ze-contact{padding:13px 14px;display:flex;gap:10px;align-items:center;cursor:pointer;border-right:3px solid transparent}.ze-contact:hover,.ze-contact.active{background:#17263f;border-right-color:#5b7cff}.ze-avatar{width:44px;height:44px;flex:0 0 44px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#00c6ff,#7c3aed);font-weight:950;overflow:hidden}.ze-avatar img{width:100%;height:100%;object-fit:cover}.ze-contact-info{min-width:0;flex:1}.ze-contact-name{font-weight:850}.ze-last{font-size:11px;opacity:.6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ze-unread{background:#2563eb;color:#fff;border-radius:999px;padding:3px 7px;font-size:10px;font-weight:900}
#ze-chat-main{display:flex;flex-direction:column;min-width:0}#ze-chat-head{min-height:72px;background:#fff;border-bottom:1px solid #e5e7eb;display:flex;align-items:center;gap:12px;justify-content:space-between;padding:0 15px}.ze-head-left{display:flex;align-items:center;gap:10px}.ze-presence{font-size:11px;color:#64748b}.ze-callbar{display:flex;gap:6px}.ze-callbtn{border:0;border-radius:12px;padding:9px 11px;background:#eef2ff;color:#273b90;font-weight:900;cursor:pointer}.ze-callbtn:hover{filter:brightness(.97)}
#ze-chat-messages{flex:1;overflow:auto;padding:18px;background:linear-gradient(#f8fafc,#eef2ff)}.ze-msg{position:relative;max-width:74%;margin:8px 0;padding:10px 13px;border-radius:17px;box-shadow:0 2px 9px #0000000d;word-wrap:break-word}.ze-msg.me{margin-left:auto;background:#dbeafe;border-bottom-right-radius:5px;color:#0f172a}.ze-msg.them{background:#fff;border-bottom-left-radius:5px;color:#111827}.ze-msg.deleted{font-style:italic;opacity:.65}.ze-time{font-size:9px;opacity:.5;margin-top:4px;text-align:right}.ze-tools{display:none;gap:4px;position:absolute;top:-28px;right:0}.ze-msg:hover .ze-tools{display:flex}.ze-mini{border:1px solid #dbe2ef;background:#fff;border-radius:8px;font-size:11px;padding:4px 6px;cursor:pointer}.ze-reaction{position:absolute;bottom:-8px;right:8px;background:#fff;border:1px solid #dbe2ef;border-radius:999px;padding:2px 6px;font-size:11px}
#ze-call-stage{position:fixed;inset:0;z-index:100028;background:#050816ee;display:none;align-items:center;justify-content:center;padding:18px}.ze-call-window{width:min(1000px,96vw);height:min(760px,92vh);position:relative;background:#0b1220;border-radius:24px;overflow:hidden;box-shadow:0 25px 100px #000a}.ze-call-stage{}#ze-call-stage.on{display:flex}.ze-remote-view{width:100%;height:100%;object-fit:contain;background:#050816}.ze-local-view{position:absolute;right:18px;top:18px;width:min(230px,32vw);aspect-ratio:16/9;object-fit:cover;background:#111827;border-radius:16px;border:2px solid #ffffff55;box-shadow:0 10px 30px #0008}.ze-call-controls{position:absolute;left:50%;bottom:18px;transform:translateX(-50%);display:flex;gap:8px;padding:8px;background:#0f172acc;border:1px solid #ffffff18;border-radius:18px;backdrop-filter:blur(12px)}.ze-call-control{border:0;border-radius:13px;padding:11px 14px;background:#1e293b;color:#fff;font-weight:900;cursor:pointer}.ze-call-control.end{background:#dc2626}.ze-call-label{position:absolute;left:18px;top:18px;color:#fff;font-weight:900;background:#0f172bcc;padding:8px 11px;border-radius:12px;z-index:2}.ze-emoji-grid{display:grid;grid-template-columns:repeat(8,1fr);gap:5px;width:100%}.ze-emoji-grid button{border:0;background:#eef2ff;border-radius:10px;padding:7px;font-size:23px;cursor:pointer}.ze-emoji-tabs{display:flex;gap:5px;width:100%;margin-bottom:6px}.ze-emoji-tabs button{border:0;background:#e5e7eb;border-radius:9px;padding:6px 8px;cursor:pointer}.ze-emoji-tabs button.active{background:#c7d2fe}#ze-chat-compose{display:flex;gap:8px;padding:10px;background:#fff;border-top:1px solid #e5e7eb;align-items:center}#ze-chat-input{flex:1;border:1px solid #d1d5db;border-radius:14px;padding:11px 13px;outline:0}#ze-chat-send{border:0;border-radius:12px;padding:10px 15px;font-weight:900;background:#2563eb;color:#fff;cursor:pointer}.ze-typing{font-size:11px;color:#64748b;padding:0 16px 7px;background:#fff;min-height:17px}.ze-emoji{border:0;background:#f1f5f9;border-radius:12px;padding:9px;cursor:pointer}.ze-note{font-size:10px;color:#64748b;padding:5px 15px;background:#fff}
#ze-chat-launch{position:fixed;left:18px;bottom:88px;z-index:100005;border:0;border-radius:17px;padding:12px 16px;background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;font-weight:950;box-shadow:0 12px 35px #0005;cursor:pointer}.ze-modal{position:fixed;inset:0;z-index:100020;display:grid;place-items:center;background:#0008}.ze-modal-box{width:min(420px,92vw);background:#fff;border-radius:22px;padding:22px;color:#111827;box-shadow:0 25px 80px #0008}.ze-modal-actions{display:flex;gap:8px;margin-top:16px}.ze-modal-actions button{flex:1;border:0;border-radius:12px;padding:11px;font-weight:900;cursor:pointer}.ze-accept{background:#16a34a;color:#fff}.ze-reject{background:#fee2e2;color:#991b1b}.ze-call-status{position:fixed;right:18px;bottom:18px;z-index:100030;background:#101827;color:#fff;border-radius:18px;padding:12px 15px;display:none;box-shadow:0 15px 50px #0007}.ze-call-status.on{display:block}.ze-call-status small{display:block;opacity:.7;margin-top:3px}
@media(max-width:700px){#ze-chat-app{grid-template-columns:1fr;height:95vh}.ze-msg{max-width:84%}.ze-callbar .ze-callbtn{font-size:0}.ze-callbar .ze-callbtn:first-child:after{content:'📞';font-size:17px}.ze-callbar .ze-callbtn:nth-child(2):after{content:'🎥';font-size:17px}}
`;
 document.head.appendChild(s);
 const root=document.createElement('div');root.id='ze-social';root.innerHTML=`<div id="ze-chat-app"><aside id="ze-chat-side"><div id="ze-chat-brand">💬 Zeyad Chat <small style="display:block;font-size:10px;opacity:.55">رسائل • مكالمات • محافظات</small></div><input id="ze-chat-search" placeholder="بحث بالاسم أو المحافظة..."><div id="ze-social-tools"><button id="ze-tab-chats" class="active">💬 الدردشة</button><button id="ze-tab-status">⭕ الحالات</button><button id="ze-tab-mod">🛡️ المشرفين</button></div><div id="ze-contacts"></div><div id="ze-status-panel"></div><div id="ze-mod-panel"></div></aside><main id="ze-chat-main"><header id="ze-chat-head"><div class="ze-head-left"><div class="ze-avatar" id="ze-head-avatar">💬</div><div><div id="ze-chat-title">اختر محادثة</div><div class="ze-presence" id="ze-presence"></div></div></div><div class="ze-callbar"><button class="ze-callbtn" id="ze-audio-call">📞 اتصال صوتي</button><button class="ze-callbtn" id="ze-video-call">🎥 مكالمة فيديو</button><button id="ze-chat-close" class="ze-callbtn">✕</button></div></header><div id="ze-chat-messages"></div><div id="ze-chat-typing" class="ze-typing"></div><div class="ze-note">🔒 الرسائل مشفرة أثناء النقل عبر HTTPS عند النشر. المكالمات تستخدم WebRTC بين الطرفين.</div><div id="ze-sticker-panel" class="ze-sticker-panel"></div><form id="ze-chat-compose"><button type="button" class="ze-emoji" id="ze-emoji">😊</button><input id="ze-chat-input" autocomplete="off" placeholder="اكتب رسالة..."><button id="ze-chat-send">إرسال</button></form></main></div>`;document.body.appendChild(root);
 const callStage=document.createElement('div');callStage.id='ze-call-stage';callStage.innerHTML='<div class="ze-call-window"><div class="ze-call-label" id="ze-call-label">مكالمة فيديو 🔒</div><video id="ze-stage-remote" class="ze-remote-view" autoplay playsinline></video><video id="ze-stage-local" class="ze-local-view" autoplay playsinline muted></video><audio id="ze-stage-audio" autoplay></audio><div class="ze-call-controls"><button class="ze-call-control" id="ze-mute">🎙️ كتم</button><button class="ze-call-control" id="ze-camera">📷 الكاميرا</button><button class="ze-call-control end" id="ze-end">📵 إنهاء</button></div></div>';document.body.appendChild(callStage);
 const launch=document.createElement('button');launch.id='ze-chat-launch';launch.textContent='💬 Zeyad Chat';document.body.appendChild(launch);
 const callStatus=document.createElement('div');callStatus.className='ze-call-status';callStatus.id='ze-call-status';document.body.appendChild(callStatus);
 let people=[],active=null,data={},pc=null,localStream=null,currentCall=null,pollTimer=null,signalTimer=null;
 const state=()=>{try{return JSON.parse(localStorage.getItem('zek_state')||'{}')}catch{return{}}};
 const api=window.api || (async(url,opt={})=>{opt.headers={...(opt.headers||{}),...(state().token?{Authorization:'Bearer '+state().token}:{})};if(opt.body&&typeof opt.body==='object'){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(opt.body)}const r=await fetch(url,opt),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'error');return j});
 const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function renderContacts(filter=''){const q=filter.trim().toLowerCase(),box=document.getElementById('ze-contacts');box.innerHTML='';people.filter(p=>(p.name+' '+(p.governorate||'')).toLowerCase().includes(q)).forEach(p=>{const el=document.createElement('div');el.className='ze-contact '+(p.id===active?'active':'');const avatar=p.avatar?`<img src="${esc(p.avatar)}" alt="">`:esc((p.name||'?')[0]);const last=(data[p.id]||[]).slice(-1)[0];el.innerHTML=`<div class="ze-avatar">${avatar}</div><div class="ze-contact-info"><div class="ze-contact-name">${esc(p.name)}</div><div class="ze-last">${p.online?'🟢 متصل الآن':'⚪ غير متصل'} · ${esc(p.governorate||'محافظة غير محددة')}${last?' · '+esc(last.deleted?'رسالة محذوفة':last.text):''}</div></div>${p.unread?`<span class="ze-unread">${p.unread}</span>`:''}`;el.onclick=async()=>{active=p.id;renderContacts(document.getElementById('ze-chat-search').value);await loadMessages()};box.appendChild(el)})}
 async function loadPeople(){if(!state().token){people=[];renderContacts();return}try{people=await api('/api/social/users');if(!active||!people.some(p=>p.id===active))active=people[0]?.id||null;renderContacts(document.getElementById('ze-chat-search').value);if(active)await loadMessages()}catch{}}
 async function loadMessages(){if(!active||!state().token)return;try{data[active]=await api('/api/social/messages?with='+encodeURIComponent(active));renderMessages()}catch{}}
 function renderMessages(){const p=people.find(x=>x.id===active);if(!p)return;document.getElementById('ze-chat-title').textContent=p.name;document.getElementById('ze-presence').textContent=(p.online?'🟢 متصل الآن':'⚪ غير متصل')+' · '+(p.governorate||'محافظة غير محددة');document.getElementById('ze-head-avatar').innerHTML=p.avatar?`<img src="${esc(p.avatar)}" alt="">`:esc((p.name||'?')[0]);const box=document.getElementById('ze-chat-messages');box.innerHTML='';(data[active]||[]).forEach(m=>{const d=document.createElement('div');d.className='ze-msg '+(m.me?'me':'them')+(m.deleted?' deleted':'');let tools=m.me&&!m.deleted?`<div class="ze-tools"><button class="ze-mini" data-act="edit">تعديل</button><button class="ze-mini" data-act="delete">حذف</button></div>`:'';const isSticker=!m.deleted&&String(m.text||'').startsWith('STICKER:');const body=isSticker?`<div class="ze-sticker-big">${esc(String(m.text).slice(8))}</div>`:`<div>${esc(m.text)}</div>`;d.innerHTML=`${body}${tools}<div class="ze-time">${new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} ${m.me?(m.read?'✓✓':'✓'):''}${m.edited?' · معدلة':''}</div>${m.reaction?`<span class="ze-reaction">${esc(m.reaction)}</span>`:''}`;d.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>messageAction(b.dataset.act,m));d.onclick=e=>{if(e.target.closest('.ze-tools'))return;if(!m.deleted&&confirm('إضافة ❤️ لهذه الرسالة؟'))react(m.id,m.reaction?'':'❤️')};box.appendChild(d)});box.scrollTop=box.scrollHeight}
 async function messageAction(a,m){if(a==='delete'&&confirm('حذف الرسالة؟'))await api('/api/social/messages/delete',{method:'POST',body:{id:m.id}});if(a==='edit'){const t=prompt('عدّل الرسالة:',m.text);if(t&&t.trim())await api('/api/social/messages/edit',{method:'POST',body:{id:m.id,text:t.trim()}})}await loadMessages()}
 async function react(id,reaction){try{await api('/api/social/messages/react',{method:'POST',body:{id,reaction}});await loadMessages()}catch{}}
 
const emojiSets={'😊':['😀','😃','😄','😁','😆','😅','😂','🤣','😊','😇','🙂','🙃','😉','😌','😍','🥰','😘'],'❤️':['❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔','❤️‍🔥','💕','💖','💗','💓','💞','💘'],'🔥':['🔥','✨','⭐','🌟','💫','⚡','🎉','🎊','💯','🚀','🏆','👑','💎','🎮','🎵','🐧','🎀'],'👍':['👍','👎','👏','🙌','🙏','🤝','💪','👌','✌️','🤞','🫶','👋','🖐️','☝️','💅','🫡']};
function fillStickers(){const p=document.getElementById('ze-sticker-panel');p.innerHTML='<div class="ze-emoji-tabs">'+Object.keys(emojiSets).map((k,i)=>`<button type="button" class="${i===0?'active':''}" data-cat="${k}">${k}</button>`).join('')+'</div><div class="ze-emoji-grid" id="ze-emoji-grid"></div>';const draw=k=>{document.getElementById('ze-emoji-grid').innerHTML=emojiSets[k].map(x=>`<button type="button">${x}</button>`).join('');document.querySelectorAll('.ze-emoji-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.cat===k));document.querySelectorAll('.ze-emoji-grid button').forEach(b=>b.onclick=async()=>{if(!active||!state().token)return;try{await api('/api/social/messages',{method:'POST',body:{to:active,text:'STICKER:'+b.textContent}});p.classList.remove('open');await loadMessages()}catch{}})};document.querySelectorAll('.ze-emoji-tabs button').forEach(b=>b.onclick=()=>draw(b.dataset.cat));draw(Object.keys(emojiSets)[0])}
async function showStatuses(){
 document.getElementById('ze-contacts').style.display='none';document.getElementById('ze-mod-panel').style.display='none';const p=document.getElementById('ze-status-panel');p.style.display='block';
 try{const rows=await api('/api/social/statuses');p.innerHTML=`<button id="ze-add-status" style="width:100%;border:0;border-radius:13px;padding:11px;background:#2563eb;color:#fff;font-weight:900;cursor:pointer">➕ إضافة حالة (24 ساعة)</button>`+rows.map(x=>`<div class="ze-status-card"><div class="ze-status-top"><div class="ze-avatar">${x.avatar?`<img src="${esc(x.avatar)}">`:esc((x.name||'?')[0])}</div><div>${esc(x.name)}<div style="font-size:9px;color:#64748b">${esc(x.governorate||'')}</div></div></div>${x.sticker?`<div class="ze-sticker-big">${esc(x.sticker)}</div>`:''}${x.text?`<div class="ze-status-text">${esc(x.text)}</div>`:''}</div>`).join('')||'<div style="padding:20px;color:#64748b">لا توجد حالات حالياً.</div>';
 document.getElementById('ze-add-status').onclick=async()=>{const text=prompt('اكتب الحالة (حتى 300 حرف):');if(text?.trim()){await api('/api/social/statuses',{method:'POST',body:{text:text.trim()}});showStatuses()}}
 }catch{p.innerHTML='<div style="padding:20px">تعذر تحميل الحالات.</div>'}
}
async function showModGroup(){
 document.getElementById('ze-contacts').style.display='none';document.getElementById('ze-status-panel').style.display='none';const p=document.getElementById('ze-mod-panel');p.style.display='block';
 const u=state().user||{};if(!['owner','moderator'].includes(u.role)){
   p.innerHTML='<button id="ze-mod-login" style="width:100%;border:0;border-radius:13px;padding:11px;background:#7c3aed;color:#fff;font-weight:900;cursor:pointer">🔐 دخول المشرفين بالكود</button><p style="font-size:11px;color:#64748b;line-height:1.6">بعد تسجيل الدخول يصبح حسابك مشرفاً وتقدر تدخل جروب المشرفين.</p>';
   document.getElementById('ze-mod-login').onclick=async()=>{if(!state().token){window.openLogin?.();return}const code=prompt('اكتب كود المشرف:');if(!code)return;try{const j=await api('/api/moderator/login',{method:'POST',body:{code}});const s=state();s.user=j.user;localStorage.setItem('zek_state',JSON.stringify(s));showModGroup()}catch(e){window.toast?.('كود المشرف غير صحيح')}}
   return;
 }
 try{const rows=await api('/api/moderators/group');p.innerHTML='<div style="font-weight:950;margin:5px 0 10px">🛡️ جروب المشرفين</div>'+rows.map(m=>`<div class="ze-mod-msg ${m.me?'me':''}"><b>${esc(m.name)}</b><span class="ze-role">${esc(m.role)}</span><div>${esc(m.text)}</div><small>${new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')+'<div style="display:flex;gap:6px;margin-top:8px"><input id="ze-mod-input" style="flex:1;border:1px solid #d1d5db;border-radius:12px;padding:10px" placeholder="رسالة للمشرفين..."><button id="ze-mod-send" style="border:0;border-radius:12px;background:#2563eb;color:#fff;padding:10px 13px;font-weight:900">إرسال</button></div>';p.scrollTop=p.scrollHeight;
 document.getElementById('ze-mod-send').onclick=async()=>{const i=document.getElementById('ze-mod-input');if(i.value.trim()){await api('/api/moderators/group',{method:'POST',body:{text:i.value.trim()}});showModGroup()}}
 }catch{p.innerHTML='<div style="padding:20px">تعذر تحميل جروب المشرفين.</div>'}
}
function switchSocialTab(tab){document.getElementById('ze-contacts').style.display=tab==='chats'?'block':'none';document.getElementById('ze-status-panel').style.display=tab==='status'?'block':'none';document.getElementById('ze-mod-panel').style.display=tab==='mod'?'block':'none';document.querySelectorAll('#ze-social-tools button').forEach(b=>b.classList.remove('active'));document.getElementById('ze-tab-'+(tab==='chats'?'chats':tab)).classList.add('active');if(tab==='status')showStatuses();if(tab==='mod')showModGroup();}
fillStickers();
document.getElementById('ze-tab-chats').onclick=()=>switchSocialTab('chats');document.getElementById('ze-tab-status').onclick=()=>switchSocialTab('status');document.getElementById('ze-tab-mod').onclick=()=>switchSocialTab('mod');

document.getElementById('ze-chat-search').oninput=e=>renderContacts(e.target.value);
 let typingDebounce=0;document.getElementById('ze-chat-input').addEventListener('input',()=>{if(!active)return;clearTimeout(typingDebounce);api('/api/social/typing',{method:'POST',body:{to:active}}).catch(()=>{});typingDebounce=setTimeout(()=>{},800)});
 document.getElementById('ze-chat-compose').onsubmit=async e=>{e.preventDefault();const input=document.getElementById('ze-chat-input'),text=input.value.trim();if(!text)return;if(!state().token){window.openLogin?.();return}if(!active)return;try{await api('/api/social/messages',{method:'POST',body:{to:active,text}});input.value='';await loadMessages();await loadPeople()}catch{window.toast?.('تعذر إرسال الرسالة')}};
 document.getElementById('ze-emoji').onclick=()=>document.getElementById('ze-sticker-panel').classList.toggle('open');document.getElementById('ze-chat-close').onclick=()=>root.classList.remove('open');launch.onclick=()=>{root.classList.add('open');if(!state().token){window.openLogin?.();return}loadPeople()};
 async function typingPoll(){if(!active||!root.classList.contains('open'))return;try{const j=await api('/api/social/typing?with='+encodeURIComponent(active));document.getElementById('ze-chat-typing').textContent=j.typing?'يكتب الآن...':''}catch{}}
 async function incomingPoll(){if(!state().token)return;try{const calls=await api('/api/calls/incoming');if(calls[0]&&!currentCall)showIncoming(calls[0])}catch{}}
 function showIncoming(c){const m=document.createElement('div');m.className='ze-modal';m.innerHTML=`<div class="ze-modal-box"><h2>${c.video?'🎥':'📞'} ${c.video?'مكالمة فيديو':'مكالمة صوتية'} واردة</h2><p><b>${esc(c.name)}</b> بيتصل بيك.</p><div class="ze-modal-actions"><button class="ze-accept">قبول</button><button class="ze-reject">رفض</button></div></div>`;document.body.appendChild(m);m.querySelector('.ze-reject').onclick=async()=>{await api('/api/calls/status',{method:'POST',body:{callId:c.id,status:'rejected'}}).catch(()=>{});m.remove()};m.querySelector('.ze-accept').onclick=async()=>{m.remove();await acceptCall(c)} }
 function status(t,sub=''){callStatus.innerHTML=`📞 ${esc(t)}<small>${esc(sub)}</small>`;callStatus.classList.add('on')}
 async function createPeer(callId,other,isCaller,video){const cfg=await api('/api/webrtc/config');pc=new RTCPeerConnection({iceServers:cfg.iceServers||[],iceCandidatePoolSize:4});pc.onicecandidate=e=>{if(e.candidate)api('/api/calls/signal',{method:'POST',body:{callId,to:other,type:'candidate',data:JSON.stringify(e.candidate)}}).catch(()=>{})};pc.ontrack=e=>{const stream=e.streams[0];if(video){const v=document.getElementById('ze-stage-remote');v.srcObject=stream;document.getElementById('ze-call-stage').classList.add('on')}else{document.getElementById('ze-stage-audio').srcObject=stream}};pc.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(pc.connectionState))endCall(false)};const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:!!video});localStream=stream;document.getElementById('ze-stage-local').srcObject=stream;document.getElementById('ze-stage-local').style.display=video?'block':'none';document.getElementById('ze-stage-remote').style.display=video?'block':'none';document.getElementById('ze-call-label').textContent=video?'مكالمة فيديو مشفرة بالنقل 🔒':'مكالمة صوتية مشفرة بالنقل 🔒';document.getElementById('ze-call-stage').classList.add('on');stream.getTracks().forEach(t=>pc.addTrack(t,stream));currentCall={callId,other,video};startSignalPoll();return pc}
 async function startCall(video=false){if(!active)return window.toast?.('اختار شخص الأول');if(!navigator.mediaDevices?.getUserMedia)return window.toast?.('المكالمات تحتاج HTTPS أو localhost');try{const j=await api('/api/calls/start',{method:'POST',body:{to:active,video}});status(video?'جاري الاتصال بالفيديو...':'جاري الاتصال الصوتي...',people.find(p=>p.id===active)?.name||'');await createPeer(j.callId,active,true,video);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await api('/api/calls/signal',{method:'POST',body:{callId:j.callId,to:active,type:'offer',data:JSON.stringify(offer)}})}catch(e){window.toast?.('تعذر بدء المكالمة: '+e.message);endCall(false)}}
 async function acceptCall(c){try{status('مكالمة مع '+c.name);await api('/api/calls/status',{method:'POST',body:{callId:c.id,status:'accepted'}});await createPeer(c.id,c.fromId||c.from,false,!!c.video);currentCall.callId=c.id;currentCall.other=c.fromId||c.from;startSignalPoll()}catch{window.toast?.('تعذر قبول المكالمة')}}
 async function startSignalPoll(){clearInterval(signalTimer);signalTimer=setInterval(async()=>{if(!currentCall)return;try{const rows=await api('/api/calls/signals?callId='+encodeURIComponent(currentCall.callId));for(const x of rows){const d=JSON.parse(x.data);if(x.type==='offer'){await pc.setRemoteDescription(d);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await api('/api/calls/signal',{method:'POST',body:{callId:currentCall.callId,to:x.fromId,type:'answer',data:JSON.stringify(ans)}})}else if(x.type==='answer'){await pc.setRemoteDescription(d)}else if(x.type==='candidate'){try{await pc.addIceCandidate(d)}catch{}}else if(x.type==='bye'){endCall(false)}}}catch{}},700)}
 async function endCall(send=true){clearInterval(signalTimer);if(send&&currentCall)await api('/api/calls/status',{method:'POST',body:{callId:currentCall.callId,status:'ended'}}).catch(()=>{});if(localStream)localStream.getTracks().forEach(t=>t.stop());localStream=null;if(pc){pc.close();pc=null}document.getElementById('ze-stage-remote').srcObject=null;document.getElementById('ze-stage-local').srcObject=null;document.getElementById('ze-stage-audio').srcObject=null;document.getElementById('ze-call-stage').classList.remove('on');currentCall=null;callStatus.classList.remove('on')}
 document.getElementById('ze-audio-call').onclick=()=>startCall(false);document.getElementById('ze-video-call').onclick=()=>startCall(true);callStatus.onclick=()=>endCall(true);document.getElementById('ze-end').onclick=()=>endCall(true);document.getElementById('ze-mute').onclick=()=>{const t=localStream?.getAudioTracks?.()[0];if(t){t.enabled=!t.enabled;document.getElementById('ze-mute').textContent=t.enabled?'🎙️ كتم':'🔇 تشغيل الصوت'}};document.getElementById('ze-camera').onclick=()=>{const t=localStream?.getVideoTracks?.()[0];if(t){t.enabled=!t.enabled;document.getElementById('ze-camera').textContent=t.enabled?'📷 الكاميرا':'🚫 الكاميرا مغلقة'}};
 setInterval(()=>{if(root.classList.contains('open')&&state().token){loadPeople();loadMessages();typingPoll()}incomingPoll()},3500);incomingPoll();
 window.ZeyadChat={open:()=>{root.classList.add('open');loadPeople()},close:()=>root.classList.remove('open')};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initSocial);else initSocial();
})();
